export const FIND_EXTREMUM_LEVELS = {
  LEVELS_INTERVAL: '15',
  LEVELS_INTERVAL_MICRO: '5',
  LEVELS_INTERVAL_MACRO: '60',
  MID_START: 10,
  MID_START_MICRO: 7,
  MID_START_MACRO: 7,
  LEVELS_COUNT: 7,
  PERIOD_BAR_COUNT: 500,
  ATR_COEFFICIENT_CLOSE_LEVEL: 0.35,
  LAST_BARS_COUNT: 5,
};

export const FIND_EXTREMUM_ACTUAL_LEVELS = {
  ATR_COEFFICIENT_ACTUAL_LEVEL: 1,
  ATR_COEFFICIENT_ACTUAL_LEVEL_RANGE: 2,
};
