export const FIND_EXTREMUM_LEVELS_INTERVAL = '5';
export const FIND_EXTREMUM_LEVELS_PERIOD_BAR_COUNT = 500;
export const FIND_EXTREMUM_LEVELS_LEVELS_COUNT = 2;
export const FIND_EXTREMUM_LEVELS_MID_START = 10;
export const FIND_EXTREMUM_LEVELS_ATR_COEFFICIENT_ACTUAL_LEVEL = 0.15;

export const FIND_EXTREMUM_LEVELS = {
  LEVELS_INTERVAL: '5',
  PERIOD_BAR_COUNT: 500,
  LEVELS_COUNT: 2,
  MID_START: 10,
  ATR_COEFFICIENT_CLOSE_LEVEL: 0.25,
};

export const FIND_EXTREMUM_ACTUAL_LEVELS = {
  ATR_COEFFICIENT_ACTUAL_LEVEL: 0.15,
};
